---
title: ACTUBI.COM - LE MEILLEUR DE L'INFORMATION
timezone: UTC
collections:
  categories:
    title: Categories
    output: true
  posts:
    title: Posts
    output: true
  rubriques:
    title: Rubriques
    output: true
  radios:
    title: Radios
    output: true
  sliders:
    title: Sliders
    output: true
  auteurs:
    title: Auteurs
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@revovision.ca
tel: "+221 33 846 25 26"
description: 'Notre but est de vous offir le meilleur de linformation en temps reel et de maniere impartiale'
baseurl: 
url: www.actubi.com
adresse: 32, Boulevard Djily Mbaye, Dakar Plateau
twitter_url: https://twitter.com
instagram_url: https://instagram.com
youtube_url: https://youtube.com
facebook_url: https://facebook.com/Actubicom-1597282660369524
googleplus_url: https://googleplus.com
github_username: jekyll
markdown: kramdown
plugins:
- jekyll-feed
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock